import os
from dotenv import load_dotenv
from enum import Enum

# Load environment variables from .env file
load_dotenv()

GLOBAL_PROJECT = os.getenv("GLOBAL_PROJECT")
GLOBAL_PROJECT_INBOUNDCALL_STR = 'InboundCall'
GLOBAL_PROJECT_INBOUNDCALL_ID = 9999999900
GLOBAL_PROJECT_OUTBOUNDCALL_STR = 'OutboundCall'
GLOBAL_PROJECT_OUTBOUNDCALL_ID = 9999999901
GLOBAL_PROJECT_OPENAI_SESSION_UPDATE_CONFIG_ID = 9999999902
GLOBAL_PROJECT_OPENAI_CHAT_COMPLETIONS_CONFIG_ID = 9999999903



GLOBAL_PROJECT_ID = GLOBAL_PROJECT_OUTBOUNDCALL_ID # by default, OutboundCall
if GLOBAL_PROJECT == GLOBAL_PROJECT_OUTBOUNDCALL_STR:
    GLOBAL_PROJECT_ID = GLOBAL_PROJECT_OUTBOUNDCALL_ID
elif GLOBAL_PROJECT == GLOBAL_PROJECT_INBOUNDCALL_STR:
    GLOBAL_PROJECT_ID = GLOBAL_PROJECT_INBOUNDCALL_ID
else:
    GLOBAL_PROJECT_ID = GLOBAL_PROJECT_OUTBOUNDCALL_ID

# Twilio 語音設置
TWILIO_VOICE_SETTINGS = {
    "WELCOME_MESSAGE": "唯 你好",
    "LANGUAGE": "zh-TW",
    "VOICE": "Alice - redirected",
    "INIT_PAUSE_LENGTH_SEC": 0.5
}

WAITTIME_BEFORE_CALL_function_call_closethecall = 10


