import os
from dotenv import load_dotenv
from enum import Enum

# Load environment variables from .env file
load_dotenv()

GLOBAL_PROJECT = os.getenv("GLOBAL_PROJECT")
GLOBAL_PROJECT_INBOUNDCALL_STR = 'InboundCall'
GLOBAL_PROJECT_INBOUNDCALL_ID = 0
GLOBAL_PROJECT_OUTBOUNDCALL_STR = 'OutboundCall'
GLOBAL_PROJECT_OUTBOUNDCALL_ID = 1



GLOBAL_PROJECT_ID = GLOBAL_PROJECT_OUTBOUNDCALL_ID # by default, OutboundCall
if GLOBAL_PROJECT == GLOBAL_PROJECT_OUTBOUNDCALL_STR:
    GLOBAL_PROJECT_ID = GLOBAL_PROJECT_OUTBOUNDCALL_ID
elif GLOBAL_PROJECT == GLOBAL_PROJECT_INBOUNDCALL_STR:
    GLOBAL_PROJECT_ID = GLOBAL_PROJECT_INBOUNDCALL_ID
else:
    GLOBAL_PROJECT_ID = GLOBAL_PROJECT_OUTBOUNDCALL_ID



